pool:
  vmImage: ubuntu-latest

stages:
  - stage: ci
    displayName: Continuous Integration
    jobs:
      - job: build
        displayName: Build Project Assets
        container: mcr.microsoft.com/dotnet/sdk:7.0
        steps:
          - script: |
              dotnet publish \
              --configuration Release \
              --output out \
              --runtime win-x64 \
              --self-contained \
              -p:PublishSingleFile=true \
              -p:EnableCompressionInSingleFile=true \
              -p:PublishReadyToRun=true \
              -p:DebugType=embedded
            displayName: Publish .NET console project
          - publish: out/Contoso.Spaces.Console.exe
            displayName: Upload console app artifact
            artifact: console-app