pool:
  vmImage: ubuntu-latest

stages:
  - stage: ci
    displayName: Continuous Integration
    jobs:
      - job: build
        displayName: Build Project Assets
        container: mcr.microsoft.com/dotnet/sdk:7.0
        steps:
          - script: |
              dotnet publish \
              --configuration Release \
              --output out \
              --runtime win-x64 \
              --self-contained \
              -p:PublishSingleFile=true \
              -p:EnableCompressionInSingleFile=true \
              -p:PublishReadyToRun=true \
              -p:DebugType=embedded
            displayName: Publish .NET console project
          - publish: out/Contoso.Spaces.Console.exe
            displayName: Upload console app artifact
            artifact: console-app
          - script: |
              dotnet pack \
              --output pkg \
              -p:Version=1.0.0
            displayName: Package .Net tool
          - publish: pkg/Contoso.Spaces.Console.1.0.0.nupkg
            displayName: upload package artifact
            artifact: nuget-package
      - job: release
        displayName: Release on Nuget
        dependsOn: build
        container: mcr.microsoft.com/dotnet/sdk:7.0
        steps:
        - download: current
          displayName: Download package artifact
          artifact: nuget-package
        - script: |
          dotnet nuget push \
          Contoso.Spaces.Console.1.0.0.nupkg \
          --skip-duplicate \
          --api-key $(nuget-api-key) \
          --source https://api.nuget.org/v3/index.json
        displayName: Push to Nuget.org
        workingDirectory: $(Pipeline.Workspace)/nuget-package


